FROM python:3.6.4

# 设置工作目录
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# 添加应用
COPY . /usr/src/app

# pip.conf
RUN mkdir -p /root/.pip
COPY ./pip.conf /root/.pip/

# 安装依赖
RUN pip install -r requirements.txt

# 运行服务
CMD python manage.py run -h 0.0.0.0
